#!/usr/bin/env python3
"""Install the current Groundcraft source through a generated local marketplace."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_PLUGIN = ROOT / "plugins" / "groundcraft"
SOURCE_MARKETPLACE = ROOT / ".agents" / "plugins" / "marketplace.json"
CODEX_HOME = Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")).expanduser().resolve()
STATE_ROOT = CODEX_HOME / "groundcraft"
DEV_MARKETPLACE = STATE_ROOT / "dev-marketplace"
GENERATED_MARKER = ".groundcraft-dev-marketplace"
CONFIG = CODEX_HOME / "config.toml"
CACHEBUSTER = (
    CODEX_HOME / "skills" / ".system" / "plugin-creator" / "scripts" / "update_plugin_cachebuster.py"
)
PLUGIN_ID = "groundcraft@groundcraft"


def run(command: list[str]) -> subprocess.CompletedProcess[str]:
    completed = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, check=False)
    if completed.returncode:
        detail = completed.stderr.strip() or completed.stdout.strip() or f"exit {completed.returncode}"
        raise RuntimeError(f"{' '.join(command)}: {detail}")
    return completed


def configured_marketplace() -> tuple[str, str] | None:
    try:
        config = tomllib.loads(CONFIG.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return None
    except tomllib.TOMLDecodeError as exc:
        raise RuntimeError(f"invalid Codex config: {exc}") from exc
    entry = config.get("marketplaces", {}).get("groundcraft")
    if not isinstance(entry, dict):
        return None
    return str(entry.get("source_type", "")), str(entry.get("source", ""))


def plugin_is_configured() -> bool:
    try:
        config = tomllib.loads(CONFIG.read_text(encoding="utf-8"))
    except (FileNotFoundError, tomllib.TOMLDecodeError):
        return False
    return PLUGIN_ID in config.get("plugins", {})


def stage_marketplace(parent: Path) -> Path:
    parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=".dev-marketplace-", dir=parent))
    shutil.copytree(
        SOURCE_PLUGIN, staging / "plugins" / "groundcraft",
        ignore=shutil.ignore_patterns(".DS_Store", "__pycache__", "*.pyc"),
    )
    marketplace = staging / ".agents" / "plugins" / "marketplace.json"
    marketplace.parent.mkdir(parents=True)
    shutil.copy2(SOURCE_MARKETPLACE, marketplace)
    (staging / GENERATED_MARKER).write_text("generated by scripts/install-local.py\n", encoding="utf-8")
    return staging


def publish_marketplace(staging: Path) -> None:
    if STATE_ROOT.is_symlink():
        raise RuntimeError(f"refusing symlinked Groundcraft state root: {STATE_ROOT}")
    if DEV_MARKETPLACE.is_symlink():
        raise RuntimeError(f"refusing symlinked dev marketplace: {DEV_MARKETPLACE}")
    if DEV_MARKETPLACE.exists():
        if not DEV_MARKETPLACE.is_dir() or not (DEV_MARKETPLACE / GENERATED_MARKER).is_file():
            raise RuntimeError(f"refusing unmanaged dev marketplace: {DEV_MARKETPLACE}")
        shutil.rmtree(DEV_MARKETPLACE)
    staging.replace(DEV_MARKETPLACE)


def install() -> str:
    run([sys.executable, str(ROOT / "scripts" / "validate.py")])
    if not CACHEBUSTER.is_file():
        raise RuntimeError(f"plugin-creator cachebuster helper not found: {CACHEBUSTER}")

    staging = stage_marketplace(DEV_MARKETPLACE.parent)
    try:
        plugin = staging / "plugins" / "groundcraft"
        run([sys.executable, str(CACHEBUSTER), str(plugin)])
        version = json.loads(
            (plugin / ".codex-plugin" / "plugin.json").read_text(encoding="utf-8")
        )["version"]
        publish_marketplace(staging)
    finally:
        if staging.exists():
            shutil.rmtree(staging)

    desired = ("local", str(DEV_MARKETPLACE))
    current = configured_marketplace()
    if current != desired:
        if plugin_is_configured():
            run(["codex", "plugin", "remove", PLUGIN_ID, "--json"])
        if current is not None:
            run(["codex", "plugin", "marketplace", "remove", "groundcraft", "--json"])
        run(["codex", "plugin", "marketplace", "add", str(DEV_MARKETPLACE), "--json"])
    run(["codex", "plugin", "add", PLUGIN_ID, "--json"])
    return str(version)


def main() -> int:
    try:
        version = install()
    except (OSError, RuntimeError, KeyError, json.JSONDecodeError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(f"Groundcraft local installed: {version}")
    print(f"Source: {ROOT}")
    print("Start a new Codex thread to load it.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
